### PR TITLE
Successfully Added ico file via upload

### PR DESCRIPTION
**Pull request by aust-jacobite**
I successfully created and uploaded the effective favicon ico file.

### CODE REVIEW

**Comment by aust-jacobite** [comment]
I just edited the white spaces noticed.

**Comment by elimisteve** [comment]
@aust-jacobite This looks pretty awesome! Could I see it with the _E_ moved ~1 pixel right, and then I think it's perfect! :tada:

**Comment by elimisteve** [comment]
Well done, @aust-jacobite! Merged :smile: :tada: :tada: :tada:

**Comment by elimisteve** [comment]
#progress

**Pull request merged**
